<?php 
// Сперва добавим хуки на страницу регистрации
function agreement_form_alter(&$form, &$form_state, $form_id){
     switch ($form_id) {  
      case 'user_register_form':
       $form['terms_of_use'] = array(
          '#type' => 'checkbox',
          '#title' => ' Я принимаю <a href="/agreement"> Условия пользовательского соглашения</a>',
          '#required' => TRUE,
          '#weight' => 15,
        );
      break;
    }  
  }

/**
 * Implements hook_perm().
 */
function agreement_permission() {
 return array(
   'administer Agreement' => array(
     'title' => t('Administer Agreement'),
   ),
   'view Agreement' => array(
     'title' => t('View Terms and Conditions'),
   ),
 );
}

/**
 * Implements hook_access().
 */
function agreement_access($op, $node, $account) {
  return ($op == 'view' && (user_access('view Agreement') || user_access('administer Agreement')));
}

function agreement_menu() {
  $items = array();

    $items['admin/config/people/agreement'] = array(
        'access arguments'  => array('administer Agreement'),
        'description'       => ('Настройка лицензионного соглашения.'),
        'page callback'     => 'drupal_get_form',
        'page arguments'    => array('agreement_config_form'),
        'title'             => t('Agreement settings'),
        'type'              => MENU_NORMAL_ITEM,
    );

    $items['agreement'] = array(
        'title' => 'Условия пользовательского соглашения',
        'page callback' => 'agreement_page_callback',
        'access arguments' => array('view Agreement'),
        'type' => MENU_CALLBACK,
 );

  return $items;
}

function agreement_config_form($form, &$form_state) {
    $form = array();

    $form['agreement_text'] = array(
        '#type' => 'textarea',
        '#title' => t('Agreement text'),
        '#default_value' => variable_get('agreement_text', '')
    );

    return $form;
}

// Вывод на страницу
function agreement_page_callback() {

  $agreement_content = variable_get('agreement_text');

return $agreement_content;
}