<?php
/**
 * Created by PhpStorm.
 * User: Happensit
 * Date: 13.01.14
 * Time: 9:19
 */

function banner_redirect_form_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == "bunner_node_form") {
    $form['actions']['submit']['#submit'][] = 'banner_redirect_form_submit';
  }
}
function banner_redirect_form_submit ($form, &$form_state) {
  $form_state['redirect'] = '<front>';
  $messages = drupal_get_messages('status');
  drupal_set_message('Баннер на главной обновлён!');
}